// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:velo_toulouse_redesign/core/utils/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYl0ElQKkpN7jGkY-iLQ3ND7oZxNxPyc',
    appId: '1:107736598732:web:3df4497be5192cd26f5a69',
    messagingSenderId: '107736598732',
    projectId: 'velo-toulouse-71603',
    authDomain: 'velo-toulouse-71603.firebaseapp.com',
    databaseURL: AppConfig.firebaseUrl,
    storageBucket: AppConfig.storageBucketUrl,
    measurementId: 'G-CW6FEJPRCE',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYtHP_PPJz17iciTN0ISac25POFhu1tM',
    appId: '1:107736598732:android:fe0ed86b28276db16f5a69',
    messagingSenderId: '107736598732',
    projectId: 'velo-toulouse-71603',
    databaseURL: AppConfig.firebaseUrl,
    storageBucket: AppConfig.storageBucketUrl,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBur7Md28ab6jSwtpoONqHcnQi5bzT4vUo',
    appId: '1:107736598732:ios:49e819381c8b33466f5a69',
    messagingSenderId: '107736598732',
    projectId: 'velo-toulouse-71603',
    databaseURL: AppConfig.firebaseUrl,
    storageBucket: AppConfig.storageBucketUrl,
    iosBundleId: 'com.example.veloToulouseRedesign',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBur7Md28ab6jSwtpoONqHcnQi5bzT4vUo',
    appId: '1:107736598732:ios:49e819381c8b33466f5a69',
    messagingSenderId: '107736598732',
    projectId: 'velo-toulouse-71603',
    databaseURL: AppConfig.firebaseUrl,
    storageBucket: AppConfig.storageBucketUrl,
    iosBundleId: 'com.example.veloToulouseRedesign',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTYl0ElQKkpN7jGkY-iLQ3ND7oZxNxPyc',
    appId: '1:107736598732:web:dbf6ef56bf5f5c106f5a69',
    messagingSenderId: '107736598732',
    projectId: 'velo-toulouse-71603',
    authDomain: 'velo-toulouse-71603.firebaseapp.com',
    databaseURL: AppConfig.firebaseUrl,
    storageBucket: AppConfig.storageBucketUrl,
    measurementId: 'G-8D3RM1VDVL',
  );
}
